class Constants:
    GO_HOME = 1
    GO_BACK = 2
    GO_LOGO = 3
    GO_DISCONT = 4
    GO_SYSTEM = 5
    GO_PRODUCTS_LIST = 6
    GO_SUBCATEGORY = 7
    GO_PRODUCT_DETAILS = 8
    GO_PAYMENT_METODS = 10

    ST_WAIT = 0
    ST_SUBCATEGORY = 1
    ST_PRODUCT_LIST = 2
    ST_PRODUCT_DETAILS = 3
    ST_PAYMET_METODS =4

    ITEM_CATEGORY = 0
    ITEM_PRODUCTS_LIST = 1
    ITEM_PRODUCT_DETAILS = 2
    PAYMET_METODS = 4
